In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('PMData0.csv')
df.head()

,item_id,date,steps,sedentary,LPA,MPA,VPA,sleep_duration,duration_score,deep_sleep_in_minutes,resting_heart_rate,restlessness
0,p01,2019-11-01,17873.0,636,245,58,72,429,38.0,27.0,53.0,0.053635
1,p01,2019-11-02,13118.0,709,202,43,56,430,37.0,36.0,53.0,0.078978
2,p01,2019-11-03,14312.0,648,262,63,45,422,38.0,38.0,52.0,0.093491
3,p01,2019-11-04,10970.0,760,230,23,28,399,38.0,37.0,53.0,0.064851
4,p01,2019-11-05,16186.0,737,263,22,56,362,36.0,26.0,54.0,0.093185

In [3]:
df.isnull().sum()

item_id                    0
date                       0
steps                    194
sedentary                  0
LPA                        0
MPA                        0
VPA                        0
sleep_duration             0
duration_score           415
deep_sleep_in_minutes    415
resting_heart_rate       415
restlessness             415
dtype: int64

In [4]:
#forward filling
df.fillna(method='ffill', inplace=True)

/var/folders/yr/hy7b_nl94zg6x7p5xd0ypr180000gn/T/ipykernel_49528/832376248.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [5]:
df.isnull().sum()

item_id                  0
date                     0
steps                    0
sedentary                0
LPA                      0
MPA                      0
VPA                      0
sleep_duration           0
duration_score           0
deep_sleep_in_minutes    0
resting_heart_rate       0
restlessness             0
dtype: int64

In [7]:
def calculate_lebel(df):
    if ((df['steps'] < 5000) and ((df['VPA']*2 + df['MPA'])*7 < 90) and (df['LPA'] >=0)): #sedentary
        return 0
    elif ((df['steps'] >= 5000) and ((df['VPA']*2 + df['MPA'])*7 >= 90) and (df['VPA']*2 + df['MPA'])*7 < 210) or (df['steps'] >= 5000 and df['steps'] <= 7499): #LPA
        return 1
    elif ((df['steps'] >= 5000) and ((df['VPA']*2 + df['MPA'])*7 >= 210) and (df['VPA']*2 + df['MPA'])*7 < 300) or (df['steps'] >= 7500 and df['steps'] <= 9999): #MPA
        return 2
    elif ((df['steps'] >= 5000) and ((df['VPA']*2 + df['MPA'])*7 >= 300) and (df['VPA']*2 + df['MPA'])*7 < 360) or (df['steps'] >= 10000 and df['steps'] <= 12499): #MPA
        return 3
    elif ((df['steps'] >= 5000) and (df['VPA']*2 + df['MPA'])*7 >= 360) or (df['steps'] >= 12500): #VPA
        return 4
    elif (df['steps'] < 5000):
        return 0

df['active'] = df.apply(calculate_lebel, axis=1)
df.to_csv("PMData1.csv", index=False)

In [8]:
df.head()

,item_id,date,steps,sedentary,LPA,MPA,VPA,sleep_duration,duration_score,deep_sleep_in_minutes,resting_heart_rate,restlessness,active
0,p01,2019-11-01,17873.0,636,245,58,72,429,38.0,27.0,53.0,0.053635,4
1,p01,2019-11-02,13118.0,709,202,43,56,430,37.0,36.0,53.0,0.078978,4
2,p01,2019-11-03,14312.0,648,262,63,45,422,38.0,38.0,52.0,0.093491,4
3,p01,2019-11-04,10970.0,760,230,23,28,399,38.0,37.0,53.0,0.064851,3
4,p01,2019-11-05,16186.0,737,263,22,56,362,36.0,26.0,54.0,0.093185,4